import os

BASE_DIR = os.path.abspath(os.path.dirname(__file__))
UPLOAD_FOLDER = os.path.join(BASE_DIR, '..', 'data', 'uploads')
ALLOWED_EXTENSIONS = {'pdf', 'doc', 'docx'}



data_science_skills = ['queries', 'beautifulsoup', 'ms excel', 'mathematics', 'selenium', 'html',
                       'analytical skills', 'statsmodels','ai', 'improvement', 'analyze', 'metrics',
                       'forecasting', 'analytics', 'analytical', 'mysql', 'postgresql', 'database', 
                       'writing', 'excel','regulations', 'algorithms', 'scipy', 'opencv', 'reports', 
                       'eda', 'jupyter', 'presentations', 'modeling', 'audit', 'technical skills',
                       'schedule', 'nltk', 'iso', 'xgboost', 'segmentation', 'github', 'seaborn',
                       'keras', 'distribution', 'investigation', 'tableau','probability', 'analysis', 
                       'r', 'technical', 'programming', 'web scraping', 'research', 'pandas', 
                       'statistical analysis', 'numpy', 'predictive analysis', 'tensorflow', 'hypothesis',
                       'matplotlib', 'scikit-learn', 'information technology', 'machine learning', 'cloud',
                       'streamlit', 'mining', 'python', 'data analytics', 'deep learning', 'testing',
                       'training', 'clustering & classification', 'data analysis', 'engineering', 
                       'data visualization', 'quantitative analysis', 'statistics', 'flask',
                       'statistical modeling', 'pytorch', 'data mining', 'aws', 'sql'] 

keyword_variations = {
    "queries": ["queries", "database_queries"],
    "beautifulsoup": ["beautifulsoup", "Beautiful_Soup", "BeautifulSoup_Library"],
    "ms_excel": ["ms_excel", "Microsoft_Excel", "Excel", "Advanced_Excel"],
    "mathematics": ["mathematics", "math"],
    "selenium": ["selenium", "Selenium_WebDriver"],
    "html": [ "HTML", "HTML_Language"],
    "analytical_skills": ["analytical_skills", "analytical", "analytical_abilities"],
    "statsmodels": ["statsmodels", "Stats_Models", "StatsModels_Library"],
    "ai": [ "artificial_intelligence", "AI"],
    "improvement": ["improvement", "continuous_improvement", "process_improvement"],
    "analyze": ["analyze", "analysis", "analyzing"],
    "metrics": ["metrics", "performance_metrics", "measurement_metrics"],
    "forecasting": ["forecasting", "predictive_forecasting", "forecasting_analysis"],
    "analytics": ["analytics", "data_analytics", "business_analytics" , "data_analysis"],
    "mysql": ["mysql", "MySQL", "MySQL_Database"],
    "postgresql": ["postgresql", "PostgreSQL", "PostgreSQL_Database"],
    "database": ["database", "databases", "database_management"],
    "writing": ["writing", "report_writing", "technical_writing"],
    "regulations": ["regulations", "compliance_regulations", "regulatory_standards"],
    "algorithms": ["algorithms", "algorithm_development", "algorithm_design"],
    "scipy": ["scipy", "SciPy", "SciPy_Library"],
    "opencv": ["opencv", "OpenCV", "OpenCV_Library"],
    "reports": ["reports", "reporting", "report_generation"],
    "eda": [ "exploratory_data_analysis", "EDA"],
    "jupyter": ["jupyter", "Jupyter_Notebook", "Jupyter_Lab"],
    "presentations": ["presentations", "presentation_skills", "data_presentations"],
    "modeling": ["modeling", "data_modeling", "statistical_modeling"],
    "audit": ["audit", "auditing", "data_audit"],
    "technical_skills": ["technical_skills", "technical_expertise", "technical_abilities"],
    "schedule": ["schedule", "scheduling", "time_management"],
    "nltk": [ "NLTK", "Natural_Language_Toolkit"],
    "iso": ["iso", "ISO_standards", "ISO_compliance"],
    "xgboost": [ "XGBoost", "XGBoost_Algorithm"],
    "segmentation": ["segmentation", "market_segmentation", "data_segmentation"],
    "github": [ "GitHub", "version_control" , "git"],
    "seaborn": ["seaborn", "Seaborn", "Seaborn_Library"],
    "keras": ["keras", "Keras", "Keras_Library"],
    "distribution": ["distribution", "data_distribution", "statistical_distribution"],
    "investigation": ["investigation", "data_investigation", "investigative_analysis"],
    "tableau": [ "Tableau", "Tableau_Software"],
    "probability": ["probability", "probability_theory", "probability_analysis"],
    "analysis": ["analysis", "data_analysis", "statistical_analysis"],
    "R": ["R", "R_Language", "R_Programming"],
    "technical": ["technical", "technical_skills", "technical_knowledge"],
    "programming": ["programming", "coding", "software_development"],
    "web_scraping": ["webscraping", "Web_Scraping", "web_data_extraction"],
    "research": ["research", "data_research", "research_analysis"],
    "pandas": [ "Pandas", "Pandas_Library"],
    "statistical_analysis": ["statistical_analysis", "statistical_testing", "statistical_evaluation"],
    "numpy": ["numpy", "NumPy_Library"],
    "predictive_analysis": ["predictive_analysis", "predictive_modeling", "predictive_analytics"],
    "tensorflow": [ "TensorFlow", "TensorFlow_Library"],
    "hypothesis": ["hypothesis", "hypothesis_testing", "hypothesis_analysis"],
    "matplotlib": [ "Matplotlib", "Matplotlib_Library"],
    "scikit_learn": ["scikit_learn", "Scikit-Learn", "Scikit_Learn_Library"],
    "information_technology": ["information_technology", "IT_skills"],
    "machine_learning": ["machinelearning", "Machine_Learning", "ML"],
    "cloud": ["cloud", "cloud_computing", "cloud_technology"],
    "streamlit": [ "Streamlit", "Streamlit_Library"],
    "mining": ["mining", "data_mining", "mining_techniques"],
    "python": ["python", "Python_Language", "Python_Programming"],
    "deep_learning": ["deeplearning", "Deep_Learning", "DL"],
    "testing": ["testing", "data_testing", "testing_procedures"],
    "training": ["training", "data_training", "model_training"],
    "clustering_&_classification": ["clustering_&_classification", "clustering", "classification"],
    "engineering": ["engineering", "data_engineering", "engineering_skills"],
    "data_visualization": ["data_visualization", "data_viz", "visualization"],
    "quantitative_analysis": ["quantitative_analysis", "quantitative", "quantitative_research"],
    "statistics": ["statistics", "statistical_methods", "statistical_analysis"],
    "flask": ["flask", "Flask", "Flask_Framework"],
    "statistical_modeling": ["statistical_modeling", "statistical_analysis", "modeling"],
    "pytorch": ["pytorch", "PyTorch", "PyTorch_Library"],
    "aws": [ "AWS", "Amazon_Web_Services"],
    "sql": [ "SQL", "Structured_Query_Language"]
}
